export const PPT_ERROR_CODES = {
  EMPTY_BULLETS: "EMPTY_BULLETS",
  MISSING_TABLE_HEADERS: "MISSING_TABLE_HEADERS",
  INVALID_IMAGE_PATH: "INVALID_IMAGE_PATH",
  MISSING_IMAGE_PATH: "MISSING_IMAGE_PATH",
  MISSING_IMAGE_FILE: "MISSING_IMAGE_FILE",
  UNSUPPORTED_BLOCK: "UNSUPPORTED_BLOCK",
} as const;

export type PptErrorCode = (typeof PPT_ERROR_CODES)[keyof typeof PPT_ERROR_CODES];
